# Generated by Django 5.1.2 on 2024-10-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caluser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='caluser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
