export const content = [
  {
    id: 1,
    title: 'Math Assignment',
    src: '1z-E_KOC2L0',
    type: 'Video',
    status: 'Pending',
    grade: 'A',
  },
  {
    id: 2,
    title: 'Science Project',
    src: '',
    type: 'Assessment',
    status: 'In Progress',
    grade: 'B',
  },
  {
    id: 3,
    title: 'History Essay',
    src: '',
    content:
      'This is a detailed paragraph about World History. It covers the major events, significant figures, and important dates that shaped the world as we know it today. From ancient civilizations to modern times, this essay provides a comprehensive overview of historical developments. It also discusses the impact of these events on contemporary society and how they have influenced current global dynamics. The essay is well-researched and offers insights into the cultural, political, and economic aspects of history, making it a valuable resource for students and history enthusiasts alike.',
    type: 'Article',
    status: 'Completed',
    grade: 'A+',
  },
  {
    id: 4,
    title: 'English Literature',
    src: '',
    type: 'Assessment',
    status: 'Pending',
    grade: 'B+',
  },
  {
    id: 5,
    title: 'Computer Science Assignment',
    src: 'dQw4w9WgXcQ',
    type: 'Video',
    status: 'In Progress',
    grade: 'A',
  },
  {
    id: 6,
    title: 'Chemistry Lab Report',
    src: '',
    type: 'Assessment',
    status: 'Completed',
    grade: 'A-',
  },
  {
    id: 7,
    title: 'Geography Presentation',
    content:
      'This is a detailed paragraph about Geography. It explores the physical features of the Earth, including mountains, rivers, and oceans. The presentation also delves into the various climatic zones and their characteristics, as well as the impact of human activities on the environment. It highlights the importance of sustainable practices and conservation efforts to protect our planet. Additionally, the presentation covers the cultural and economic aspects of different regions, providing a holistic understanding of Geography. This comprehensive overview makes it an excellent resource for students and educators.',
    type: 'Article',
    status: 'Pending',
    grade: 'B-',
  },
  {
    id: 8,
    title: 'Art Project',
    src: '',
    type: 'Assessment',
    status: 'In Progress',
    grade: 'A+',
  },
]
