FROM node:22

WORKDIR /app/backend/activity_engine

COPY backend/activity_engine/package*.json /app/backend/activity_engine

RUN npm install
RUN npm install nodemon -g

EXPOSE 9000

CMD ["npm", "run", "dev"]