# Generated by Django 5.1.2 on 2024-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollmentbind',
            name='enrollmentDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
