# Generated by Django 5.1.2 on 2024-10-31 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_chapterassessmentbind_options'),
        ('students', '0002_alter_courseenrollmentbind_enrollmentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrollmentbind',
            old_name='enrollmentDate',
            new_name='enrollment_date',
        ),
        migrations.CreateModel(
            name='AssessmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('init_accessed', models.DateTimeField(auto_now_add=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.assessment')),
            ],
            options={
                'ordering': ['last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField()),
                ('assessments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.assessmentprogress')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
            ],
            options={
                'ordering': ['last_accessed'],
            },
        ),
        migrations.AddField(
            model_name='courseenrollmentbind',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.chapterprogress'),
        ),
    ]
