# Generated by Django 5.1.2 on 2024-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_enrollmentdate_courseenrollmentbind_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseenrollmentbind',
            options={'verbose_name': 'Enrolled Course', 'verbose_name_plural': 'Enrolled Courses'},
        ),
        migrations.AlterField(
            model_name='courseenrollmentbind',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
