# Generated by Django 5.1.2 on 2024-10-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_courseenrollmentbind_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterprogress',
            name='assessments',
        ),
        migrations.RemoveField(
            model_name='chapterprogress',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='courseenrollmentbind',
            name='progress',
        ),
        migrations.DeleteModel(
            name='AssessmentProgress',
        ),
        migrations.DeleteModel(
            name='ChapterProgress',
        ),
    ]
