# Generated by Django 5.1.2 on 2024-11-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_chapterprogress_assessments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollmentbind',
            name='progress',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
