# Generated by Django 5.1.2 on 2024-10-30 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_assessment_format_alter_assessment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechapterbind',
            options={'ordering': ['order'], 'verbose_name': 'Course Chapter', 'verbose_name_plural': 'Course Chapters'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AlterField(
            model_name='coursechapterbind',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter', verbose_name='Chapter Title'),
        ),
        migrations.AlterField(
            model_name='coursechapterbind',
            name='order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
