# Generated by Django 5.1.2 on 2024-10-30 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursechapterbind_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterassessmentbind',
            name='course',
        ),
        migrations.AddField(
            model_name='chapterassessmentbind',
            name='assessment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapterassessmentbind',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='coursechapterbind',
            name='order',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
