# Generated by Django 5.1.2 on 2024-10-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_chapterassessmentbind_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterassessmentbind',
            options={'ordering': ['order'], 'verbose_name': 'Chapter Assessment', 'verbose_name_plural': 'Chapter Assessments'},
        ),
    ]
