# Generated by Django 5.1.2 on 2024-11-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_chapterassessmentbind_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='assessmentIDs',
            new_name='assessments',
        ),
    ]
