# Generated by Django 4.2.16 on 2024-12-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0011_remove_videosegment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videosegment',
            name='unique_sequence_per_video',
        ),
        migrations.AddConstraint(
            model_name='videosegment',
            constraint=models.UniqueConstraint(fields=('video', 'start_time'), name='unique_sequence_per_video'),
        ),
    ]
