# Generated by Django 4.2.16 on 2024-12-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_content', '0013_remove_videosegment_unique_sequence_per_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosegment',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='The sequence of this segment within the video.'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='videosegment',
            constraint=models.UniqueConstraint(fields=('video', 'sequence'), name='unique_sequence_per_video'),
        ),
    ]
