name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'  # Recommended to use LTS version
    - name: Change to frontend directory
      run: cd frontend
    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      working-directory: ./frontend
    - name: Build
      run: npm run build
      working-directory: ./frontend
    - name: Deploy to Firebase
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project cal-frontend
      working-directory: ./frontend
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
