name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  build-core-engine:
    name: Build and Push Docker Image (Core Engine)
    uses: ./.github/workflows/build.yml

  deploy-core-engine:
    name: Deploy to Production (Core Engine)
    needs: build-core-engine
    runs-on: ubuntu-latest

    environment: "Core Engine Production"

    steps:
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'hello-cloud-run'
          image: ${{ needs.build-core-engine.outputs.image }}

